alias cdprj='cd /prj/dyumnin/designw.in'
alias cdweb='cd /prj/dyumnin/designw.in/web'
alias cdng='cd /prj/dyumnin/designw.in/ng2.rc5/app/project'
alias tmux="tmux -u -2 new-session -A -s main"
alias addtime="sudo kidtimer addtime srihari 30"
alias tmuxdp="cdweb;cd ../hdl/ec/datapower;\tmux -u -2 new-session -A -s main"
alias gitolite="cd /prj/gitolite"
alias emacs="/opt/bin/emacs"
alias ghdl="/opt/bin/ghdl"
alias vit="perl /opt/bin/vit"
alias intensetask="task intensivate"
alias python3=python36
alias phone="cat /prj/records/phone"
